name: Create Azure VM

on:
  push:
    branches:
      - main

jobs:
  create-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.32.0

      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Azure VM
        run: |
          az vm create \
            --resource-group <your-resource-group> \
            --name <your-vm-name> \
            --image UbuntuLTS \
            --admin-username <your-username> \
            --admin-password <your-password> \
            --size Standard_DS1_v2
